apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: websrv
spec:
  containers:
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/
      readOnly: true
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf

