apiVersion: extensions/v1beta1
#apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "route"
     nginx.ingress.kubernetes.io/session-cookie-expires: "129600"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "129600"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: websrv-main
          servicePort: 80
      - path: /s1
        backend:
          serviceName: websrv-s1
          servicePort: 80
      - path: /s2
        backend:
          serviceName: websrv-s2
          servicePort: 80
